from .employees.employee_list import employee_list

from .home import home
from .auth.logout import logout_user

from .training_programs.training_programs_list import training_programs_list
from .training_programs.training_program_details import training_program_details
from .training_programs.training_program_form import training_program_form
from .training_programs.training_program_form import training_program_edit_form
from .training_programs.training_program_details import attendee_list
